// Configuración de Poder Absoluto H&I
export const HI_REGIMEN = {
  MODERADOR_UNICO: "isaac03.24castillo@gmail.com", //
  VERSION: "1.0.0-SUPERIOR",
  MARCAS: {
    BODEGA: "HI_COMERCIO",
    RESTAURANTE: "HI_FOOD",
    FERRETERIA: "HI_PRO",
    ZAPATERIA: "HI_FASHION",
    TIENDA: "HI_STORE"
  },
  ESTADOS: {
    SOLICITUD: "ESPERANDO_APROBACION_ISAAC",
    ACTIVO: "VINCULADO_AL_REGIMEN",
    BLOQUEADO: "ACCESO_DENEGADO"
  }
};
